# conf/model/fmm_cae.yaml

_target_: src.models.cvae.FMM_CAE
name: fmm_cae

batch_size: ${batch_size}
f1: 19
f2: 9
num_leads : ${dataset.num_features}
seq_len : ${dataset.sequence_length}
split_ecg: ${dataset.split_ecg}
max_omega: 0.20
num_warmup_epochs: 500
reconstruction_loss_weight: 1.0
coefficient_loss_weight: 1.0
coeffs_properties_dict: ???




