# conf/model/lstm_ae.yaml

_target_: src.models.ecgnet.FMM_EcgNet
name: fmm_lstm_ae

enc_units: [256, 128, 64]
dropout_rate: 0.0
add_relu: False
sequence_length: ${dataset.sequence_length}
num_features: ${dataset.num_features}

batch_size: ${batch_size}
num_leads : ${dataset.num_features}
seq_len : ${dataset.sequence_length}
split_ecg: ${dataset.split_ecg}
max_omega: 0.20
reconstruction_loss_weight: 1.0
coefficient_loss_weight: 1.0
num_warmup_epochs: 500
coeffs_properties_dict: ???