# conf/model/fmm_bert_ecg.yaml

_target_: src.models.transformer.FMM_Bert_ECG
name: fmm_bert_ecg

#Inputs
num_heads: 6
num_layers: 2
d_model: 64
dff: 128
dropout_rate: 0.1
input_vocab_size: None

batch_size: ${batch_size}
target_vocab_size: ${dataset.num_features} 
num_leads : ${dataset.num_features}
seq_len : ${dataset.sequence_length}
split_ecg: ${dataset.split_ecg}
max_omega: 0.20
reconstruction_loss_weight: 1.0
coefficient_loss_weight: 1.0
num_warmup_epochs: 30
coeffs_properties_dict: ???